SRCS = megaphone.cpp
NAME = megaphone
FLAGS = -Wall -Wextra -Werror
CC = c++ -std=c++98
RM = rm -rf

all : $(SRCS)
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean :
	$(RM) $(NAME)

fclean : clean

re : fclean all
